version: '3'

services:
  influxdb:
    image: influxdb
    ports:
      - "1234:8086"
    volumes:
      - /tmp/influxdbrelay-influx:/var/lib/influxdb

  influxdb2:
    image: influxdb
    ports:
      - "5678:8086"
    volumes:
      - /tmp/influxdbrelay-influx2:/var/lib/influxdb

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  relay:
    build:
      context: .
      dockerfile: Dockerfile.develop
    ports:
      - "9096:9096"
