[[http]]
name = "test-config"
bind-addr = "0.0.0.0:9096"
health-timeout-ms = 10000
rate-limit = 5
burst-limit = 10

[[http.output]]
name="influxdb01"
location="http://influxdb:8086/"
endpoints = {write="/write", ping="/ping", query="/query"}

[[http.output]]
name="influxdb02"
location="http://influxdb:8086/"
endpoints = {write="/write", ping="/ping", query="/query"}
buffer-size-mb=100
max-batch-kb=1000
max-delay-interval="5s"

[[http.output]]
name="influxdb03"
location="http://influxdb:8086/"
endpoints = {write="/write", ping="/ping", query="/query"}
buffer-size-mb=100
max-batch-kb=1000
max-delay-interval="5s"

[[filter]]
tag-expression = "^.{0,5}$"
measurement-expression = "^.{3,12}$"
outputs = [ "influxdb01", "influxdb03" ]

[[filter]]
tag-expression = "^.{5,12}$"
outputs = [ "influxdb02" ]
